export const members = [
    {
      name: "Rey",
      DOB: "31 January",
      DOM: "Jakarta",
      role: "Founder",
      avatar: "Rey.jpg",
    },
    {
      name: "Valen",
      DOB: "31 October",
      DOM: "Batam",
      role: "Leader",
      avatar: "Melin.jpg",
    },
    {
      name: "Fadel",
      DOB: "18 April",
      DOM: "Jakarta",
      role: "Staff",
      avatar: "Fadel.jpg",
    },
    {
      name: "Arthae",
      DOB: "25 January",
      DOM: "Kaltim",
      role: "Staff",
      avatar: "Arthae.jpg",
    },
    {
      name: "Velita",
      DOB: "11 November",
      DOM: "Batam",
      role: "Staff",
      avatar: "Velita.jpg",
    },
    {
      name: "Angelia",
      DOB: "22 Desember",
      DOM: "Kalteng",
      role: "Staff",
      avatar: "Angel.jpg",
    },
    {
      name: "Shanie",
      DOB: "4 Februari",
      DOM: "Medan",
      role: "Member",
      avatar: "Shanie.jpg",
    },
    {
      name: "Septi",
      DOB: "19 September",
      DOM: "Jakarta",
      role: "Member",
      avatar: "Septi.jpg",
    },
    {
      name: "Ajung",
      DOB: "8 Mei",
      DOM: "Bali",
      role: "Member",
      avatar: "Ajung.jpg",
    },
    {
      name: "EL",
      DOB: "15 October",
      DOM: "Manado",
      role: "Member",
      avatar: "El.jpg",
    },
    {
      name: "Sammy",
      DOB: "19 Agustus",
      DOM: "Bekasi",
      role: "Member",
      avatar: "Sammy.jpg",
    },
    {
      name: "Iksan",
      DOB: "2 January",
      DOM: "Bogor",
      role: "Member",
      avatar: "Iksan.jpg",
    },
    {
      name: "Arinie",
      DOB: "1 Juni",
      DOM: "Jakarta Barat",
      role: "Member",
      avatar: "Arinie.jpg",
    },
    {
      name: "Lita",
      DOB: "17 Desember",
      DOM: "Kalbar",
      role: "Member",
      avatar: "Lita.jpg",
    },
    {
      name: "Sofia",
      DOB: "8 Agustus",
      DOM: "Jakarta Selatan",
      role: "Member",
      avatar: "Sofia.jpg",
    },
    {
      name: "Ghifari",
      DOB: "28 Maret",
      DOM: "Jakarta",
      role: "Member",
      avatar: "Ghifari.jpg",
    },
    {
      name: "Olif",
      DOB: "23 Februari",
      DOM: "Semarang",
      role: "Member",
      avatar: "Olif.jpg",
    },
    {
      name: "Roe",
      DOB: "23 September",
      DOM: "Bekasi",
      role: "Member",
      avatar: "Roe.jpg",
    },
    {
      name: "Arul",
      DOB: "17 Agustus",
      DOM: "Tangerang",
      role: "Member",
      avatar: "Arul.jpg",
    },
    {
      name: "Mbul",
      DOB: "25 Desember",
      DOM: "Tangerang",
      role: "Member",
      avatar: "Mbul.jpg",
    },
    {
      name: "Joo",
      DOB: "18 Februari",
      DOM: "Batam",
      role: "Member",
      avatar: "Joo.jpg",
    },
    {
      name: "Bule",
      DOB: "14 November",
      DOM: "Bogor",
      role: "Member",
      avatar: "Bule.jpg",
    },
    {
      name: "Rio",
      DOB: "19 Maret",
      DOM: "Semarang",
      role: "Member",
      avatar: "Rio.jpg",
    },
    {
      name: "Nando",
      DOB: "19 Juni",
      DOM: "Bekasi",
      role: "Member",
      avatar: "Nando.jpg",
    },
    {
      name: "Aleta",
      DOB: "26 Mei",
      DOM: "Bekasi",
      role: "Member",
      avatar: "Aleta.jpg",
    },
    {
      name: "Valen",
      DOB: "14 Februari",
      DOM: "Jakarta",
      role: "Member",
      avatar: "Valen.jpg",
    },
    {
      name: "Rifqy",
      DOB: "28 Desember",
      DOM: "Jakarta",
      role: "Member",
      avatar: "Rifqy.jpg",
    },
  ];
